# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods', :disable_input_output_paths => true

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/flutter/flutter.git'

  pod 'camera', '~> 0.10.0'
  pod 'cloud_firestore', '~> 4.9.3'
  pod 'connectivity', '~> 3.0.6'
  pod 'firebase_auth', '~> 4.10.0'
  pod 'firebase_core', '~> 2.16.0'
  pod 'firebase_storage', '~> 11.2.8'
  pod 'flutter_facebook_auth', '~> 6.0.2'
  pod 'flutter_secure_storage', '~> 6.0.0'
  pod 'image_picker_ios', '~> 1.0.4'


  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
